[package]
name = "bbc-x"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
pom = { version = "3.4", features = ["utf8"] }
time = { version = "0.3.34", features = ["formatting", "local-offset"] }

[dev-dependencies]
tempdir = "0.3.7"
